"""
Django settings for voxliber project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 환경변수 로드
load_dotenv(BASE_DIR / ".env")

# 외부 서비스 URL
EXTERNAL_TTS_URL = os.getenv('EXTERNAL_TTS_URL')
if not EXTERNAL_TTS_URL and not os.getenv('DEBUG', 'False') == 'True':
    raise ValueError("⚠️ EXTERNAL_TTS_URL environment variable must be set in production!")

# 로그인 설정
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
APPEND_SLASH = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('DEBUG', 'False') == 'True':
        # 개발 환경에서만 기본값 사용
        SECRET_KEY = "django-insecure-4q07*j%nngs$zmv6m%*c(&3#8n=!)xnz_wjv@a=53mmaejhe7%"
    else:
        raise ValueError("⚠️ DJANGO_SECRET_KEY environment variable must be set in production!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'  # 기본값 False로 변경

# 프로덕션 호스트
ALLOWED_HOSTS = [
    'voxliber.ink',
    'www.voxliber.ink',
]

# 개발 환경
if DEBUG:
    ALLOWED_HOSTS.extend([
        'localhost',
        '127.0.0.1',
        '10.0.2.2',  # 안드로이드 에뮬레이터용
    ])

# AWS EC2 IP 추가
ec2_ip = os.getenv('AWS_EC2_IP')
if ec2_ip:
    ALLOWED_HOSTS.append(ec2_ip)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",  # CORS 지원
    "testpj",
    "main",
    "book",
    "audioBooks",
    "register",
    "user_auth",
    "mypage",
    "voice",
    'django_user_agents',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',

    
    

    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - 최상단에 위치
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django_user_agents.middleware.UserAgentMiddleware',

]

ROOT_URLCONF = "voxliber.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "voxliber.wsgi.application"

# Media files (업로드된 파일)
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'register.Users'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'

# 프로덕션: collectstatic으로 정적 파일을 모을 디렉토리
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # voxliber/static을 가리켜야 합니다
]

# 프로덕션 보안 설정
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS에서만 쿠키 전송
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG  # HTTP를 HTTPS로 리다이렉트

# CSRF 신뢰 도메인 (프로덕션)
CSRF_TRUSTED_ORIGINS = [
    'https://voxliber.ink',
    'https://www.voxliber.ink',
]

# 개발 환경에서만 localhost 추가
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ])

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# 데이터베이스 설정
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'voxliber'),
        'USER': os.getenv('DB_USER', 'chung'),
        'PASSWORD': os.getenv('DB_PASSWORD') or ('kch62213!' if DEBUG else None),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# 프로덕션 환경에서 DB 비밀번호 필수 확인
if not DEBUG and not DATABASES['default']['PASSWORD']:
    raise ValueError("⚠️ DB_PASSWORD environment variable must be set in production!")

# CORS 설정 (안드로이드 앱, 웹 앱 연동)
CORS_ALLOWED_ORIGINS = [
    'https://voxliber.ink',
    'https://www.voxliber.ink',
]

# 개발 환경에서만 localhost 허용
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend([
        'http://localhost:3000',
        'http://localhost:8000',
        'http://127.0.0.1:3000',
        'http://127.0.0.1:8000',
    ])

CORS_ALLOW_ALL_ORIGINS = False  # 명시적으로 비활성화
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',  # API Key 헤더
]