# Generated by Django 5.2.7 on 2025-11-06 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice_name", models.CharField(max_length=190)),
                ("voice_id", models.CharField(max_length=190)),
                ("sample_url", models.CharField(max_length=190)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "voice",
            },
        ),
    ]
