# Generated by Django 5.2.8 on 2026-02-18 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='광고 제목')),
                ('ad_type', models.CharField(choices=[('audio', '오디오 광고'), ('image', '이미지 광고'), ('video', '영상 광고')], max_length=10)),
                ('placement', models.CharField(choices=[('episode', '에피소드 중간'), ('chat', 'AI 채팅'), ('tts', 'TTS'), ('snap', '북스냅')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/ads/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/ads/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/ads/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/ads/thumbnails/')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='클릭 시 이동 URL')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='광고 길이(초) - 오디오/영상용')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '광고',
                'db_table': 'advertisement',
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(max_length=20)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False, verbose_name='스킵 여부 - 영상광고용')),
                ('watched_seconds', models.IntegerField(default=0, verbose_name='시청 시간(초) - 영상/오디오용')),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='advertisment.advertisement')),
            ],
            options={
                'verbose_name': '광고 노출 기록',
                'db_table': 'ad_impression',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', '월간 구독'), ('yearly', '연간 구독')], default='monthly', max_length=10)),
                ('status', models.CharField(choices=[('active', '구독 중'), ('expired', '만료'), ('cancelled', '해지')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구독 정보',
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='UserAdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message_count', models.IntegerField(default=0)),
                ('tts_count', models.IntegerField(default=0)),
                ('episode_play_count', models.IntegerField(default=0)),
                ('snap_view_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_counter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 광고 카운터',
                'db_table': 'user_ad_counter',
            },
        ),
    ]
