# Generated by Django 5.2.8 on 2026-02-18 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='public_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
