# Generated by Django 5.2.8 on 2026-02-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0002_advertisement_public_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('contact_name', models.CharField(max_length=100, verbose_name='담당자명')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='연락처')),
                ('title', models.CharField(max_length=200, verbose_name='광고 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='광고 설명')),
                ('placement', models.CharField(choices=[('episode', '에피소드 중간'), ('chat', 'AI 채팅'), ('tts', 'TTS'), ('snap', '북스냅')], max_length=20, verbose_name='희망 광고 위치')),
                ('ad_type', models.CharField(choices=[('audio', '오디오 광고'), ('image', '이미지 광고'), ('video', '영상 광고')], max_length=10, verbose_name='광고 타입')),
                ('budget', models.IntegerField(default=0, verbose_name='예산(원)')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/ad_requests/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/ad_requests/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/ad_requests/videos/')),
                ('status', models.CharField(choices=[('pending', '검토중'), ('approved', '승인'), ('rejected', '거절'), ('completed', '종료')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('advertisement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='advertisment.advertisement')),
            ],
            options={
                'verbose_name': '광고 요청',
                'db_table': 'ad_request',
            },
        ),
    ]
