# Generated by Django 5.2.8 on 2026-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0004_adrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrequest',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='랜딩 URL'),
        ),
    ]
