# Generated by Django 5.2.8 on 2026-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0005_adrequest_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cpc_bonus_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CPC 추가 단가(원) - enable_cpc_bonus=True일 때만 사용'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='enable_cpc_bonus',
            field=models.BooleanField(default=False, verbose_name='클릭 시 CPC 추가 과금 (이미지 광고용)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='min_watch_seconds',
            field=models.IntegerField(default=0, verbose_name='CPV 최소 시청/청취 초 (오디오:10, 영상:15, 이미지:0)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pricing_type',
            field=models.CharField(choices=[('cpm', 'CPM (1,000 노출당)'), ('cpv', 'CPV (완청/완시청당)'), ('cpc', 'CPC (클릭당)'), ('flat', 'Flat Rate (고정 월정액)')], default='cpm', max_length=10, verbose_name='단가 방식'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='skip_lock_seconds',
            field=models.IntegerField(default=0, verbose_name='스킵 불가 구간(초) - 영상광고 YouTube 방식 (예: 5)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='단가(원)'),
        ),
    ]
