# Generated by Django 5.2.8 on 2026-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('advertisment_img', models.ImageField(null=True, upload_to='upload/advertisment/')),
            ],
            options={
                'verbose_name': 'ai 광고 테이블',
                'db_table': 'screen_ai',
            },
        ),
    ]
