# Generated by Django 5.2.8 on 2026-02-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_screenai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', '일반'), ('payment', '결제'), ('account', '계정'), ('content', '오디오북'), ('snap', '스냅'), ('story', 'AI스토리'), ('other', '기타')], default='general', max_length=20),
        ),
    ]
