# Generated by Django 5.2.7 on 2025-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=191)),
                ("news_description", models.TextField(null=True)),
                (
                    "news_img",
                    models.ImageField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to="uploads/profile_img/",
                    ),
                ),
                ("news_link", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "뉴스",
                "db_table": "news",
            },
        ),
    ]
