# Generated by Django 5.2.8 on 2025-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('advertisment_img', models.ImageField(null=True, upload_to='upload/advertisment/')),
            ],
            options={
                'verbose_name': '광고 테이블',
                'db_table': 'advertisment',
            },
        ),
    ]
