# Generated by Django 5.2.8 on 2026-06-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_faq_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreenAI',
        ),
    ]
