# Generated by Django 5.2.8 on 2025-12-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advertisment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '스냅화면'},
        ),
    ]
