# Generated by Django 5.2.8 on 2026-06-24 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_screenai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='지출일')),
                ('title', models.CharField(max_length=200, verbose_name='항목명')),
                ('category', models.CharField(choices=[('server', '서버비'), ('marketing', '마케팅'), ('labor', '인건비'), ('api', 'API 사용료'), ('office', '사무용품'), ('other', '기타')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='금액')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/expense/', verbose_name='영수증')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '경비',
                'db_table': 'expense',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='발행일')),
                ('period', models.CharField(max_length=7, verbose_name='정산 월 (YYYY-MM)')),
                ('supply_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='공급가액')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='부가세(10%)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='합계금액')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('issued', '발행 완료'), ('cancelled', '취소')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '세금계산서',
                'db_table': 'tax_invoice',
                'ordering': ['-issue_date'],
            },
        ),
    ]
