# Generated by Django 5.2.8 on 2025-12-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='SnapBtn',
        ),
        migrations.AlterModelTable(
            name='snapbtn',
            table='snap_btn',
        ),
    ]
