# Generated by Django 5.2.8 on 2025-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_news_snapbtn_alter_snapbtn_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_img', models.ImageField(null=True, upload_to='upload/event/')),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '이벤트',
                'db_table': 'event',
            },
        ),
    ]
