# Generated by Django 5.2.7 on 2025-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
