# Generated by Django 5.2.7 on 2025-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="nickname",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
