# Generated by Django 5.2.7 on 2025-11-08 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_alter_users_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupTOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=20)),
                ("TOS_description", models.TextField()),
                ("is_required", models.BooleanField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("upload_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "회원가입 이용약관",
                "db_table": "signup_TOS",
            },
        ),
    ]
