# Generated by Django 5.2.7 on 2025-11-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_signuptos"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
