# Generated by Django 5.2.7 on 2025-11-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_users_is_profile_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
