# Generated by Django 5.2.8 on 2025-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_users_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cover_img',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/cover_img/'),
        ),
    ]
