# Generated by Django 5.2.8 on 2025-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_users_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_img',
        ),
        migrations.AddField(
            model_name='users',
            name='a',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/profile_img/'),
        ),
    ]
