# Generated by Django 5.2.8 on 2025-12-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_users_user_img_users_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='a',
            new_name='user_img',
        ),
    ]
