# Generated by Django 5.2.8 on 2026-02-27 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_users_public_uuid_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '방문 로그',
                'db_table': 'user_visit_log',
            },
        ),
    ]
