# Generated by Django 5.2.8 on 2026-06-23 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_uservisitlog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Subscription',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('plan', models.CharField(choices=[('monthly', '월간 구독'), ('yearly', '연간 구독')], default='monthly', max_length=10)),
                        ('status', models.CharField(choices=[('active', '구독 중'), ('expired', '만료'), ('cancelled', '해지')], default='active', max_length=10)),
                        ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('expires_at', models.DateTimeField()),
                        ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': '구독 정보',
                        'db_table': 'subscription',
                    },
                ),
            ],
        ),
    ]
