# Generated by Django 5.2.8 on 2026-06-23 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_ttsusagelog_ttsalert_bookauthor'),
        ('register', '0014_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='작가 여부'),
        ),
        migrations.CreateModel(
            name='AuthorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '검토 대기'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=20)),
                ('intro', models.TextField(blank=True, null=True, verbose_name='자기소개')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='포트폴리오 URL')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='거절 사유')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '작가 신청',
                'db_table': 'author_application',
            },
        ),
        migrations.CreateModel(
            name='AuthorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('settlement', '정산'), ('content', '콘텐츠'), ('tts', 'TTS'), ('rights', '저작권'), ('other', '기타')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/author_inquiry/')),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '대기'), ('answered', '답변 완료'), ('closed', '종료')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_inquiries', to='book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '작가 문의',
                'db_table': 'author_inquiry',
                'ordering': ['-created_at'],
            },
        ),
    ]
