# Generated by Django 5.2.8 on 2026-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_users_is_author_authorapplication_authorinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorapplication',
            name='intro',
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='planned_work',
            field=models.TextField(default='', verbose_name='쓰고 싶은 작품 소개'),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='policy_agreed',
            field=models.BooleanField(default=False, verbose_name='작가 정책 동의'),
        ),
    ]
