# Generated by Django 5.2.8 on 2026-06-24 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_remove_authorapplication_intro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='정산 월 (YYYY-MM)')),
                ('total_listen_seconds', models.BigIntegerField(default=0, verbose_name='청취 시간(초)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='정산 금액')),
                ('status', models.CharField(choices=[('pending', '정산 대기'), ('paid', '지급 완료'), ('cancelled', '취소')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '정산 기록',
                'db_table': 'settlement_record',
                'ordering': ['-period'],
                'unique_together': {('user', 'period')},
            },
        ),
    ]
