# Generated by Django 5.2.8 on 2026-06-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_settlementrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinquiry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='register.authorinquiry'),
        ),
    ]
