# Generated by Django 5.2.8 on 2026-06-24 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_authorinquiry_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', '월간 구독'), ('yearly', '연간 구독')], max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격(원)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '가격 플랜',
                'db_table': 'price_plan',
            },
        ),
    ]
