# Generated by Django 5.2.8 on 2026-06-26 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_priceplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', '월간 구독'), ('yearly', '연간 구독')], max_length=10)),
                ('amount', models.IntegerField(verbose_name='결제 금액(원)')),
                ('method', models.CharField(choices=[('kakao', '카카오페이'), ('naver', '네이버페이'), ('card', '신용카드'), ('toss', '토스페이'), ('admin', '관리자 처리')], default='card', max_length=10)),
                ('status', models.CharField(choices=[('paid', '결제 완료'), ('failed', '결제 실패'), ('refunded', '환불'), ('cancelled', '취소')], default='paid', max_length=10)),
                ('receipt_email', models.EmailField(blank=True, max_length=254)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제 내역',
                'db_table': 'payment_history',
                'ordering': ['-paid_at'],
            },
        ),
    ]
