# Generated by Django 5.2.8 on 2026-01-30 14:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/guide/thumbs/')),
                ('description', models.TextField(null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('guide_video', models.FileField(blank=True, null=True, upload_to='uploads/guide/video')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/guide/files/')),
                ('category', models.CharField(choices=[('soundEffect', '사운드 이펙트'), ('musicSound', '배경음'), ('page', '대사'), ('voiceChoice', '보이스 선택하기'), ('save', '임시저장'), ('emotionList', '감정리스트'), ('pageAudio', '페이지 오디오'), ('voiceSetting', '음성 설정'), ('preview', '미리듣기'), ('etc', '기타')], default='etc', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('order_num', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '오디오북 가이드',
                'db_table': 'audio_book_guide',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genres_color', models.CharField(default='#FFF', max_length=10)),
                ('genre_img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/genres_img/')),
            ],
            options={
                'verbose_name': '장르',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상품 설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch/', verbose_name='이미지')),
                ('link', models.URLField(blank=True, null=True, verbose_name='구매 링크')),
                ('is_new', models.BooleanField(default=False, verbose_name='신상품 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '굿즈',
                'verbose_name_plural': '굿즈 목록',
                'db_table': 'merchandise',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '책 태그',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100)),
                ('sample_audio', models.FileField(blank=True, null=True, upload_to='audio_samples/')),
                ('voice_image', models.ImageField(blank=True, default='uploads/voice_images/HOMEv.png/', null=True, upload_to='uploads/voice_images/HOME v.png/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voice_description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(default='ko', max_length=20)),
            ],
            options={
                'verbose_name': '음성 목록',
                'db_table': 'voice_list',
            },
        ),
        migrations.CreateModel(
            name='VoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '음성 타입',
                'db_table': 'voice_type',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='API Key 이름 (예: 안드로이드 앱)', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'db_table': 'api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundMusicLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('music_description', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='background_music/')),
                ('duration_seconds', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_music', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '배경음 라이브러리',
                'db_table': 'background_music_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/book_covers/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('audio_file', models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/introduc/')),
                ('episode_interval_weeks', models.IntegerField(default=1, help_text='에피소드 연재 주기 (주 단위)')),
                ('status', models.CharField(choices=[('ongoing', '연재 중'), ('paused', '휴재'), ('ended', '연재 종료')], default='ongoing', help_text='작품 연재 상태', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='book.genres')),
            ],
            options={
                'verbose_name': '책 정보',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='book.bookcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='book.books')),
            ],
            options={
                'verbose_name': '책 댓글',
                'db_table': 'book_comment',
            },
        ),
        migrations.CreateModel(
            name='AuthorAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='공지사항', max_length=200)),
                ('content', models.TextField(help_text='작가의 공지사항 내용')),
                ('is_pinned', models.BooleanField(default=False, help_text='상단 고정 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='book.books')),
            ],
            options={
                'verbose_name': '작가 공지사항',
                'db_table': 'author_announcement',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookSnap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('snap_title', models.CharField(blank=True, max_length=200, null=True)),
                ('snap_video', models.FileField(blank=True, null=True, upload_to='uploads/book_snaps/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/book_snaps/thumbnails/')),
                ('views', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('allow_comments', models.BooleanField(default=True)),
                ('book_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('book_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snaps', to='book.books')),
                ('booksnap_like', models.ManyToManyField(blank=True, related_name='liked_snaps', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_users', models.ManyToManyField(blank=True, related_name='viewed_snaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '북 스냅',
                'db_table': 'book_snap',
            },
        ),
        migrations.CreateModel(
            name='BookSnapComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='book.booksnapcomment')),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.booksnap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_snap_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/snippets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=300, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='book.books')),
            ],
            options={
                'verbose_name': '북 스니펫',
                'db_table': 'book_snippet',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=190)),
                ('number', models.IntegerField(default=1)),
                ('text', models.TextField(blank=True, null=True)),
                ('episode_image', models.ImageField(blank=True, null=True, upload_to='uploads/episode_images/')),
                ('audio_file', models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/audio/')),
                ('audio_timestamps', models.JSONField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='오디오 길이(초)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False, help_text='소프트 삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제 시간', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='book.books')),
            ],
            options={
                'verbose_name': '에피소드',
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.content')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='book.contentcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '콘텐츠 댓글',
                'db_table': 'content_comment',
            },
        ),
        migrations.CreateModel(
            name='EpisodeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='book.content')),
            ],
            options={
                'verbose_name': '에피소드 요약',
                'db_table': 'episode_summary',
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_seconds', models.IntegerField(default=0, help_text='청취한 시간(초)')),
                ('listened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_listened_at', models.DateTimeField(default=django.utils.timezone.now, help_text='마지막 청취 시각')),
                ('last_position', models.FloatField(default=0, help_text='마지막 재생 위치(초)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_stats', to='book.books')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_stats', to='book.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '청취 기록',
                'db_table': 'listening_history',
                'ordering': ['-last_listened_at'],
            },
        ),
        migrations.CreateModel(
            name='Poem_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('poem_audio', models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/poem/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='uploads/poem_img', verbose_name='이미지')),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('submitted', '제출됨'), ('winner', '수상작')], default='submitted', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '시 공모전 출품작',
                'db_table': 'poem_list',
            },
        ),
        migrations.CreateModel(
            name='SoundEffectLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_name', models.CharField(max_length=100)),
                ('effect_description', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sound_effects/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_effects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사운드 이팩트 라이브러리',
                'db_table': 'sound_effect_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.tags')),
            ],
            options={
                'verbose_name': '책 태그',
                'db_table': 'book_tag',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(related_name='books', through='book.BookTag', to='book.tags'),
        ),
        migrations.CreateModel(
            name='MyVoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.voicelist')),
            ],
            options={
                'verbose_name': '개인 목소리 목록',
                'db_table': 'my_voice_list',
            },
        ),
        migrations.AddField(
            model_name='voicelist',
            name='types',
            field=models.ManyToManyField(blank=True, to='book.voicetype'),
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.books')),
            ],
            options={
                'verbose_name': '책 리뷰',
                'db_table': 'book_review',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookmarkBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_books', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='book.books', verbose_name='책')),
            ],
            options={
                'verbose_name': '북마크한 책',
                'verbose_name_plural': '북마크 목록',
                'db_table': 'bookmark_book',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bookmark_bo_user_id_76cecd_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(help_text='북마크 위치(초)')),
                ('memo', models.TextField(blank=True, help_text='사용자 메모', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='book.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '북마크/메모',
                'db_table': 'content_bookmark',
                'ordering': ['position'],
                'unique_together': {('user', 'content', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='팔로우 시작일')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='팔로워')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='팔로잉')),
            ],
            options={
                'verbose_name': '팔로우',
                'verbose_name_plural': '팔로우 목록',
                'db_table': 'follow',
                'indexes': [models.Index(fields=['follower'], name='follow_followe_1b4118_idx'), models.Index(fields=['following'], name='follow_followi_88b73a_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_content_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('reading', '읽는 중'), ('completed', '완독'), ('paused', '일시중지')], default='reading', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='book.books')),
                ('current_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to='book.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '독서 진행 상황',
                'db_table': 'reading_progress',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
