# Generated by Django 5.2.8 on 2026-02-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='adult_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booksnap',
            name='adult_choice',
            field=models.BooleanField(default=False),
        ),
    ]
