# Generated by Django 5.2.8 on 2026-02-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_adult_choice_booksnap_adult_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnap',
            name='story_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
