# Generated by Django 5.2.7 on 2025-11-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genres",
            name="book",
        ),
        migrations.AddField(
            model_name="books",
            name="genres",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="book.genres",
            ),
        ),
    ]
