# Generated by Django 5.2.7 on 2025-11-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_remove_genres_book_books_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="genres",
            name="genre_img",
            field=models.ImageField(
                blank=True, max_length=1000, null=True, upload_to="uploads/genres_img/"
            ),
        ),
    ]
