# Generated by Django 5.2.8 on 2026-02-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_booksnap_story_link'),
        ('character', '0015_remove_story_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnap',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.story'),
        ),
    ]
