# Generated by Django 5.2.8 on 2026-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_booksnap_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.CharField(blank=True, help_text='작가명 (미입력 시 유저 닉네임 사용)', max_length=100, null=True),
        ),
    ]
