# Generated by Django 5.2.8 on 2026-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_add_author_name_to_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookguide',
            name='category',
            field=models.CharField(choices=[('soundEffect', '사운드 이펙트'), ('musicSound', '배경음'), ('page', '대사'), ('voiceChoice', '보이스 선택하기'), ('save', '임시저장'), ('emotionList', '감정리스트'), ('pageAudio', '페이지 오디오'), ('voiceSetting', '음성 설정'), ('preview', '미리듣기'), ('etc', '기타'), ('fast', '초보자 가이드')], default='etc', max_length=50),
        ),
    ]
