# Generated by Django 5.2.7 on 2025-11-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_tags_booktag_books_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
