# Generated by Django 5.2.7 on 2025-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_books_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
