# Generated by Django 5.2.8 on 2026-02-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_audiobookguide_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='voice_config',
            field=models.JSONField(blank=True, default=dict, help_text='캐릭터별 보이스 설정 {0: {name, voice_id}, ...}', null=True),
        ),
    ]
