# Generated by Django 5.2.8 on 2026-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_add_voice_config_to_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='draft_episode_title',
            field=models.CharField(blank=True, help_text='임시저장 에피소드 제목', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='draft_text',
            field=models.TextField(blank=True, help_text='임시저장 소설 텍스트', null=True),
        ),
    ]
