# Generated by Django 5.2.8 on 2026-02-24 05:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_add_draft_fields_to_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_type', models.CharField(choices=[('popular', '🔥 인기'), ('new', '🆕 신작'), ('short', '⚡ 짧게 듣기'), ('rated', '⭐ 고평점'), ('night', '🌙 자기 전 듣기'), ('custom', '✨ 큐레이션')], default='popular', max_length=20, verbose_name='플레이리스트 유형')),
                ('title', models.CharField(max_length=200, verbose_name='플레이리스트 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='uploads/playlists/', verbose_name='커버 이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_auto_generated', models.BooleanField(default=True, help_text='True면 주기적으로 자동 갱신, False면 관리자 수동 관리', verbose_name='자동생성 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='book.genres', verbose_name='장르')),
            ],
            options={
                'verbose_name': '장르 플레이리스트',
                'db_table': 'genre_playlist',
                'unique_together': {('genre', 'playlist_type')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='재생 순서')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='book.content', verbose_name='에피소드')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='book.genreplaylist', verbose_name='플레이리스트')),
            ],
            options={
                'verbose_name': '플레이리스트 항목',
                'db_table': 'playlist_item',
                'ordering': ['order'],
                'unique_together': {('playlist', 'content')},
            },
        ),
    ]
