# Generated by Django 5.2.4 on 2025-11-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_chapter_add_book_to_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '에피소드'},
        ),
        migrations.AddField(
            model_name='books',
            name='cover_img',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/book_covers/'),
        ),
    ]
