# Generated by Django 5.2.8 on 2026-03-02 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_books_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTTSQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_chars', models.IntegerField(default=0, verbose_name='이번 달 사용 글자 수')),
                ('total_chars', models.IntegerField(default=0, verbose_name='누적 총 사용 글자 수')),
                ('monthly_limit', models.IntegerField(default=0, verbose_name='월 한도 (0=무제한)')),
                ('is_premium', models.BooleanField(default=False, verbose_name='프리미엄 여부')),
                ('reset_date', models.DateField(blank=True, null=True, verbose_name='다음 리셋 날짜')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 TTS 생성 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tts_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TTS 사용량 쿼터',
                'db_table': 'user_tts_quota',
            },
        ),
    ]
