# Generated by Django 5.2.8 on 2026-03-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_add_user_tts_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_type',
            field=models.CharField(choices=[('audiobook', '오디오북'), ('webnovel', '웹소설')], db_index=True, default='audiobook', help_text='콘텐츠 유형 (오디오북 / 웹소설)', max_length=20),
        ),
    ]
