# Generated by Django 5.2.8 on 2026-03-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_add_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='llm_provider',
            field=models.CharField(blank=True, help_text='에피소드 작성 AI (gpt/grok/claude)', max_length=20, null=True),
        ),
    ]
