# Generated by Django 5.2.4 on 2025-11-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='audio_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/audio/'),
        ),
    ]
