# Generated by Django 5.2.8 on 2026-03-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_add_llm_provider_to_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
            ],
            options={
                'verbose_name': '오디오북',
                'verbose_name_plural': '오디오북 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('book.books',),
        ),
        migrations.CreateModel(
            name='WebNovel',
            fields=[
            ],
            options={
                'verbose_name': '웹소설',
                'verbose_name_plural': '웹소설 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('book.books',),
        ),
        migrations.CreateModel(
            name='PageAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('audio_file', models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/page_audio/')),
                ('text', models.TextField(blank=True, default='')),
                ('voice_id', models.CharField(blank=True, default='', max_length=100)),
                ('language_code', models.CharField(default='ko', max_length=10)),
                ('speed_value', models.FloatField(default=1.0)),
                ('style_value', models.FloatField(default=0.85)),
                ('similarity_value', models.FloatField(default=0.75)),
                ('webaudio_effect', models.CharField(blank=True, default='normal', max_length=50)),
                ('page_type', models.CharField(choices=[('tts', 'TTS'), ('silence', '무음'), ('duet', '듀엣')], default='tts', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_audios', to='book.content')),
            ],
            options={
                'db_table': 'page_audio',
                'ordering': ['page_number'],
                'unique_together': {('content', 'page_number')},
            },
        ),
    ]
