# Generated by Django 5.2.8 on 2025-11-27 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_content_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100)),
                ('sample_url', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_image', models.ImageField(blank=True, default='uploads/voice_images/HOMEv.png/', null=True, upload_to='uploads/voice_images/HOME v.png/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '음성 목록',
                'db_table': 'voice_list',
            },
        ),
    ]
