# Generated by Django 5.2.8 on 2025-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_voicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicelist',
            name='voice_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
