# Generated by Django 5.2.8 on 2026-03-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_page_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mix_config',
            field=models.JSONField(blank=True, help_text='믹싱 설정 {bgm:[{id,name,desc,volume,start_page,end_page}], sfx:[{id,name,desc,volume,page_number}]}', null=True),
        ),
    ]
