# Generated by Django 5.2.8 on 2025-11-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_voicelist_voice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicelist',
            name='language_code',
            field=models.CharField(default='ko', max_length=20),
        ),
    ]
