# Generated by Django 5.2.8 on 2026-03-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_content_mix_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='block_draft',
            field=models.JSONField(blank=True, help_text='블록 편집기 임시저장 (batch JSON)', null=True),
        ),
    ]
