# Generated by Django 5.2.8 on 2025-11-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_voicelist_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicelist',
            name='sample_url',
        ),
        migrations.AddField(
            model_name='voicelist',
            name='sample_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_samples/'),
        ),
    ]
