# Generated by Django 5.2.4 on 2025-11-27 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_remove_voicelist_sample_url_voicelist_sample_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusicLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('music_description', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='background_music/')),
                ('duration_seconds', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_music', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '배경음 라이브러리',
                'db_table': 'background_music_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundEffectLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_name', models.CharField(max_length=100)),
                ('effect_description', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sound_effects/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_effects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사운드 이팩트 라이브러리',
                'db_table': 'sound_effect_library',
                'ordering': ['-created_at'],
            },
        ),
    ]
