# Generated by Django 5.2.8 on 2026-06-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_content_tts_audio_file'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='booksnap',
                    name='story',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='book_type',
            field=models.CharField(choices=[('audiobook', '오디오북')], db_index=True, default='audiobook', help_text='콘텐츠 유형 (오디오북)', max_length=20),
        ),
        migrations.DeleteModel(
            name='Poem_list',
        ),
    ]
