# Generated by Django 5.2.4 on 2025-11-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_backgroundmusiclibrary_soundeffectlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='audio_timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
