# Generated by Django 5.2.8 on 2026-06-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_remove_booksnap_story_alter_books_book_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpisodeSummary',
        ),
    ]
