# Generated by Django 5.2.8 on 2025-11-28 03:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_content_audio_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSnap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snap_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploads/book_snaps/images/')),
                ('snap_video', models.FileField(blank=True, null=True, upload_to='uploads/book_snaps/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/book_snaps/thumbnails/')),
                ('booksnap_like', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('allow_comments', models.BooleanField(default=True)),
                ('book_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaps', to='book.books')),
            ],
            options={
                'verbose_name': '북 스냅',
                'db_table': 'book_snap',
            },
        ),
        migrations.CreateModel(
            name='BookSnapComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='book.booksnapcomment')),
                ('snap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.booksnap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_snap_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
