# Generated by Django 5.2.8 on 2026-06-23 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_delete_episodesummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TtsUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('char_count', models.IntegerField(default=0)),
                ('voice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_logs', to='book.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TTS 사용 기록',
                'db_table': 'tts_usage_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TtsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_content_link', '에피소드 미연결'), ('bulk_generation', '단시간 대량 생성'), ('duplicate_text', '동일 텍스트 반복'), ('monthly_spike', '월간 급증')], max_length=50)),
                ('status', models.CharField(choices=[('pending', '검토 대기'), ('reviewed', '검토 완료'), ('sent', '안내 발송'), ('dismissed', '무시')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_alerts', to=settings.AUTH_USER_MODEL)),
                ('tts_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='book.ttsusagelog')),
            ],
            options={
                'verbose_name': 'TTS 알림',
                'db_table': 'tts_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', '주 작가'), ('co', '공동 작가')], default='main', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '책 작가',
                'db_table': 'book_author',
                'unique_together': {('book', 'user')},
            },
        ),
    ]
