# Generated by Django 5.2.8 on 2025-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_booksnap_booksnapcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnap',
            name='book_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
