# Generated by Django 5.2.8 on 2025-11-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_booksnap_book_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksnap',
            name='book',
        ),
        migrations.AddField(
            model_name='booksnap',
            name='snap_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
