# Generated by Django 5.2.8 on 2026-06-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_voicelist_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicelist',
            name='voice_image',
            field=models.ImageField(blank=True, default='uploads/voice_images/HOMEv.png/', null=True, upload_to='uploads/voice_images/voice_image.png/'),
        ),
    ]
