# Generated by Django 5.2.8 on 2025-11-30 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_myvoicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvoicelist',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.books'),
        ),
    ]
