# Generated by Django 5.2.8 on 2025-11-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_myvoicelist_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='voicelist',
            name='types',
            field=models.ManyToManyField(blank=True, to='book.voicetype'),
        ),
    ]
