# Generated by Django 5.2.8 on 2025-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_voicetype_voicelist_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='audio_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/introduc/'),
        ),
    ]
