# Generated by Django 5.2.4 on 2025-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_books_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='오디오 길이(초)'),
        ),
    ]
