# Generated by Django 5.2.8 on 2025-12-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_listeninghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicetype',
            options={'verbose_name': '음성 타입'},
        ),
        migrations.AlterModelTable(
            name='voicetype',
            table='voice_type',
        ),
    ]
