# Generated by Django 5.2.8 on 2025-12-02 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_alter_voicetype_options_alter_voicetype_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnap',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_snaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='booksnap',
            name='booksnap_like',
        ),
        migrations.AddField(
            model_name='booksnap',
            name='booksnap_like',
            field=models.ManyToManyField(blank=True, related_name='liked_snaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
