# Generated by Django 5.2.4 on 2025-12-02 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_booksnap_viewed_users_remove_booksnap_booksnap_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'ordering': ['-last_listened_at'], 'verbose_name': '청취 기록'},
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='last_listened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='마지막 청취 시각'),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='last_position',
            field=models.FloatField(default=0, help_text='마지막 재생 위치(초)'),
        ),
    ]
