# Generated by Django 5.2.4 on 2025-12-02 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_alter_listeninghistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='공지사항', max_length=200)),
                ('content', models.TextField(help_text='작가의 공지사항 내용')),
                ('is_pinned', models.BooleanField(default=False, help_text='상단 고정 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='book.books')),
            ],
            options={
                'verbose_name': '작가 공지사항',
                'db_table': 'author_announcement',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
