# Generated by Django 5.2.4 on 2025-12-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_authorannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='episode_interval_weeks',
            field=models.IntegerField(default=1, help_text='에피소드 연재 주기 (주 단위)'),
        ),
    ]
