# Generated by Django 5.2.4 on 2025-12-03 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_books_episode_interval_weeks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(help_text='북마크 위치(초)')),
                ('memo', models.TextField(blank=True, help_text='사용자 메모', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='book.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '북마크/메모',
                'db_table': 'content_bookmark',
                'ordering': ['position'],
                'unique_together': {('user', 'content', 'position')},
            },
        ),
    ]
