# Generated by Django 5.2.8 on 2025-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_contentbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('guide_image', models.ImageField(blank=True, null=True, upload_to='uploads/guide/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/guide/thumbs/')),
                ('description', models.TextField(null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/guide/files/')),
                ('category', models.CharField(choices=[('recording', '녹음'), ('equipment', '장비'), ('editing', '편집'), ('voice', '보이스'), ('etc', '기타')], default='etc', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '오디오북 가이드',
                'db_table': 'audio_book_guide',
            },
        ),
    ]
