# Generated by Django 5.2.8 on 2025-12-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0036_audiobookguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookguide',
            name='category',
            field=models.CharField(choices=[('soundEffect', '사운드 이펙트'), ('musicSound', '배경음'), ('page', '대사'), ('voiceGenerate', '보이스 생성'), ('voiceChoice', '보이스 선택하기'), ('save', '임시저장'), ('emotionList', '감정리스트'), ('etc', '기타')], default='etc', max_length=50),
        ),
    ]
