# Generated by Django 5.2.8 on 2025-12-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_alter_audiobookguide_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobookguide',
            old_name='order',
            new_name='order_num',
        ),
    ]
