# Generated by Django 5.2.8 on 2025-12-04 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_rename_order_audiobookguide_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookguide',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='audiobookguide',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
