# Generated by Django 5.2.8 on 2025-12-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_alter_audiobookguide_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='toggle_write',
            field=models.BooleanField(default=True),
        ),
    ]
