# Generated by Django 5.2.8 on 2025-12-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_books_toggle_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='toggle_write',
            field=models.CharField(choices=[('ongoing', '연재 중'), ('paused', '휴재'), ('ended', '연재 종료')], default='ongoing', help_text='작품 연재 상태', max_length=10),
        ),
    ]
