# Generated by Django 5.2.8 on 2025-12-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_alter_books_toggle_write'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='toggle_write',
            new_name='status',
        ),
    ]
