# Generated by Django 5.2.8 on 2025-12-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0042_rename_toggle_write_books_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookguide',
            name='guide_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/guide/video'),
        ),
    ]
