# Generated by Django 5.2.8 on 2025-12-09 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0043_audiobookguide_guide_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='book.content')),
            ],
            options={
                'verbose_name': '에피소드 요약',
                'db_table': 'episode_summary',
            },
        ),
    ]
