# Generated by Django 5.2.8 on 2025-12-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0044_episodesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='episode_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/episode_images/'),
        ),
    ]
