# Generated by Django 5.2.8 on 2025-12-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0047_poem_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobookguide',
            name='guide_image',
        ),
        migrations.RemoveField(
            model_name='booksnap',
            name='snap_image',
        ),
    ]
