# Generated by Django 5.2.8 on 2025-12-12 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0048_remove_audiobookguide_guide_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem_list',
            options={'verbose_name': '시 공모전 출품작'},
        ),
        migrations.RemoveField(
            model_name='poem_list',
            name='sample_audio',
        ),
        migrations.AddField(
            model_name='poem_list',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='poem_list',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poem_list',
            name='status',
            field=models.CharField(choices=[('submitted', '제출됨'), ('winner', '수상작')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='poem_list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='poem_list',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poem_list',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='poem_list',
            table='poem_entry',
        ),
    ]
