# Generated by Django 5.2.8 on 2025-12-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0049_alter_poem_list_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poem_list',
            table='poem_list',
        ),
    ]
