# Generated by Django 5.2.8 on 2025-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0050_alter_poem_list_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem_list',
            name='poem_audio',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/poem/'),
        ),
    ]
