# Generated by Django 5.2.8 on 2025-12-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0051_poem_list_poem_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/snippets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='book.books')),
            ],
            options={
                'verbose_name': '북 스니펫',
                'db_table': 'book_snippet',
            },
        ),
    ]
