# Generated by Django 5.2.8 on 2025-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0052_booksnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상품 설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch/', verbose_name='이미지')),
                ('link', models.URLField(blank=True, null=True, verbose_name='구매 링크')),
                ('is_new', models.BooleanField(default=False, verbose_name='신상품 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '굿즈',
                'verbose_name_plural': '굿즈 목록',
                'db_table': 'merchandise',
            },
        ),
    ]
