# Generated by Django 5.2.8 on 2025-12-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0053_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksnippet',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
