# Generated by Django 5.2.8 on 2025-12-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0054_booksnippet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/poem_img', verbose_name='이미지'),
        ),
    ]
