# Generated by Django 5.2.8 on 2025-12-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0055_poem_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem_list',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='uploads/poem_img', verbose_name='이미지'),
        ),
    ]
