# Generated by Django 5.2.8 on 2025-12-28 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0057_booksnap_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookguide',
            name='category',
            field=models.CharField(choices=[('soundEffect', '사운드 이펙트'), ('musicSound', '배경음'), ('page', '대사'), ('voiceChoice', '보이스 선택하기'), ('save', '임시저장'), ('emotionList', '감정리스트'), ('pageAudio', '페이지 오디오'), ('voiceSetting', '음성 설정'), ('preview', '미리듣기'), ('etc', '기타')], default='etc', max_length=50),
        ),
        migrations.CreateModel(
            name='BookmarkBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일')),
                ('note', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='book.books', verbose_name='책')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_books', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '북마크한 책',
                'verbose_name_plural': '북마크 목록',
                'db_table': 'bookmark_book',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bookmark_bo_user_id_76cecd_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='팔로우 시작일')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='팔로워')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='팔로잉')),
            ],
            options={
                'verbose_name': '팔로우',
                'verbose_name_plural': '팔로우 목록',
                'db_table': 'follow',
                'indexes': [models.Index(fields=['follower'], name='follow_followe_1b4118_idx'), models.Index(fields=['following'], name='follow_followi_88b73a_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
