# Generated by Django 5.2.8 on 2026-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0058_alter_audiobookguide_category_bookmarkbook_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='삭제 시간', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='소프트 삭제 여부'),
        ),
    ]
