# Generated by Django 5.2.8 on 2026-01-30 14:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('llm_response', models.TextField()),
                ('response_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '대화목록',
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='character.conversation')),
            ],
            options={
                'db_table': 'conversation_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='user 가 지정한 LLM 이름')),
                ('prompt', models.TextField(verbose_name='user 가 지정한 프롬프트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='user 가 LLM 을 만든 시기')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='user 가 프롬프트, 목소리 변형을 했을 경우 나중에 문제가 생겼을때 원인을 찾을 수 있음')),
                ('llm_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/llm_images/')),
                ('response_mp3', models.CharField(blank=True, max_length=255, null=True, verbose_name='해당 보이스를 저장할 수 있는 mp3 파일 -> 목소리는 ai가 대답할 떄마다 기록이 덮어씌워짐')),
                ('model', models.CharField(choices=[('gpt:gpt-4o-mini', 'GPT-4o Mini'), ('grok:grok-3-mini', 'Grok-3-mini ')], default='gpt:gpt-4o-mini', max_length=20, verbose_name='gpt 모델 중 하나를 선택해서 사용할 수 있음')),
                ('language', models.CharField(default='en', max_length=10)),
                ('temperature', models.FloatField(default=1.0)),
                ('stability', models.FloatField(default=0.5)),
                ('speed', models.FloatField(default=1.0)),
                ('style', models.FloatField(default=0.5)),
                ('is_public', models.BooleanField(default=False, verbose_name='해당 LLM 을 공유 할 것인가?')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='해당 LLM 이 공유될떄 실행')),
                ('llm_like_count', models.IntegerField(default=0, verbose_name='llm이 받은 좋아요 갯수')),
                ('llm_background_image', models.ImageField(blank=True, null=True, upload_to='uploads/llm_background_images/')),
                ('invest_count', models.IntegerField(default=0)),
                ('first_sentence', models.TextField(null=True, verbose_name='첫 마디')),
                ('narrator_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrator_llms', to='book.voicelist', verbose_name='나레이션 목소리 (선택)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_set', to=settings.AUTH_USER_MODEL)),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llms', to='book.voicelist')),
            ],
            options={
                'verbose_name': 'ai 정보',
                'db_table': 'LLM',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='llm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.llm'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='character.comment', verbose_name='답글 대상 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.llm')),
            ],
            options={
                'verbose_name': 'AI 대한 댓글창',
                'db_table': 'comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='AI가 추출한 요약 (3~5문장)')),
                ('key_facts', models.JSONField(default=dict, verbose_name="중요 사실 JSON {fact: '값', ...}")),
                ('type', models.CharField(choices=[('summary', '대화 요약'), ('fact', '영구 사실'), ('event', '주요 사건')], max_length=20)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.conversation')),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='character.llm')),
            ],
            options={
                'verbose_name': '캐릭터 장기 기억',
                'db_table': 'character_memory',
            },
        ),
        migrations.CreateModel(
            name='LLMSubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, null=True, upload_to='uploads/llm_sub_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='character.llm')),
            ],
            options={
                'db_table': 'llm_sub_image',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField(verbose_name='활성화 키워드 (쉼표 또는 줄바꿈 구분)')),
                ('content', models.TextField(verbose_name='주입될 내용 (설명, 사실, 설정 등)')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위 (높을수록 먼저 주입)')),
                ('always_active', models.BooleanField(default=False, verbose_name='항상 포함?')),
                ('category', models.CharField(blank=True, choices=[('personality', '성격'), ('world', '세계관'), ('relationship', '관계')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore_entries', to='character.llm')),
            ],
            options={
                'verbose_name': '로어북 항목',
                'db_table': 'lore_entry',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_title', models.CharField(max_length=100, verbose_name='프롬프트 제목 적는칸')),
                ('prompt', models.TextField(verbose_name='프롬프트 적는 칸')),
                ('prompt_type', models.CharField(choices=[('text', '일반 프롬프트'), ('voice', '목소리 프롬프트')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prompt 정보',
                'db_table': 'prompt',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='소설/채팅 제목')),
                ('description', models.TextField(blank=True, verbose_name='스토리 간단 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='uploads/story_covers/')),
                ('genres', models.ManyToManyField(blank=True, related_name='llms', to='book.genres')),
                ('tags', models.ManyToManyField(blank=True, related_name='llms', to='book.tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소설/스토리',
                'verbose_name_plural': '소설/스토리들',
                'db_table': 'story',
            },
        ),
        migrations.AddField(
            model_name='llm',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='character.story', verbose_name='소속 스토리 (선택)'),
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('character_stats', models.JSONField(default=dict)),
                ('relationships', models.JSONField(default=dict)),
                ('inventory', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='character.conversation')),
            ],
            options={
                'db_table': 'conversation_state',
                'unique_together': {('conversation',)},
            },
        ),
        migrations.CreateModel(
            name='LLMLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.llm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_like',
                'unique_together': {('user', 'llm')},
            },
        ),
        migrations.CreateModel(
            name='HPImageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='최소 HP (이 값 이상일 때 적용)')),
                ('max_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='최대 HP (이 값 이하일 때 적용)')),
                ('extra_condition', models.CharField(blank=True, max_length=200, verbose_name='추가 조건 (예: corruption > 50, level >= 5)')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='우선순위 (숫자 높을수록 우선)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name="설명 (예: 'HP 30 이하 - 중상 상태')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hp_image_mappings', to='character.llm')),
                ('sub_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.llmsubimage', verbose_name='이 HP 범위에서 사용할 서브 이미지')),
            ],
            options={
                'verbose_name': 'HP별 이미지 매핑',
                'verbose_name_plural': 'HP별 이미지 매핑들',
                'db_table': 'hp_image_mapping',
                'ordering': ['-priority', 'min_hp', 'max_hp'],
                'unique_together': {('llm', 'min_hp', 'max_hp')},
            },
        ),
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_prompts', to='character.llm')),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.prompt')),
            ],
            options={
                'db_table': 'llm_prompt',
                'unique_together': {('llm', 'prompt')},
            },
        ),
    ]
