# Generated by Django 5.2.8 on 2026-01-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_storycomment_storylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tts_audio/', verbose_name='TTS 오디오 파일'),
        ),
    ]
