# Generated by Django 5.2.8 on 2026-02-01 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_conversationmessage_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='character.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스토리 북마크',
                'db_table': 'story_bookmark',
                'unique_together': {('user', 'story')},
            },
        ),
    ]
