# Generated by Django 5.2.8 on 2026-02-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_storybookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='adult_choice',
            field=models.BooleanField(default=False),
        ),
    ]
