# Generated by Django 5.2.8 on 2026-02-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_story_adult_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_desc_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/story_covers/desc'),
        ),
    ]
