# Generated by Django 5.2.8 on 2026-02-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_story_story_desc_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_desc_image',
            new_name='story_desc_video',
        ),
    ]
