# Generated by Django 5.2.8 on 2026-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_rename_story_desc_image_story_story_desc_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_desc_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/story_covers/desc'),
        ),
    ]
