# Generated by Django 5.2.8 on 2026-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_story_story_desc_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_desc_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/story_covers/desc/img'),
        ),
    ]
