# Generated by Django 5.2.8 on 2026-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_story_story_desc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmsubimage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
