# Generated by Django 5.2.8 on 2026-02-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_llmsubimage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='hp_after_message',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='hp_range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='hp_range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
