# Generated by Django 5.2.8 on 2026-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_conversationmessage_hp_after_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개 여부'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='공유 시간'),
        ),
    ]
