# Generated by Django 5.2.8 on 2026-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_conversation_is_public_conversation_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='second_audio',
            field=models.IntegerField(null=True, verbose_name='초 단위로 해당 소설 음성 초 세기'),
        ),
    ]
