# Generated by Django 5.2.8 on 2026-02-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_story_second_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='second_audio',
            new_name='audio_duration',
        ),
    ]
