# Generated by Django 5.2.8 on 2026-02-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_rename_second_audio_story_audio_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='audio_duration',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='오디오 길이(초)'),
        ),
    ]
