# Generated by Django 5.2.8 on 2026-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_alter_conversation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsubimage',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
