# Generated by Django 5.2.8 on 2026-02-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_llmsubimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='last_ward',
            field=models.TextField(null=True, verbose_name='마지막 말'),
        ),
    ]
