# Generated by Django 5.2.8 on 2026-02-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0018_llm_last_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llm',
            name='last_ward',
        ),
        migrations.CreateModel(
            name='LastWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, null=True, upload_to='uploads/llm_sub_images/')),
                ('ward', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_ward', to='character.llm')),
            ],
            options={
                'db_table': 'last_ward',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
