# Generated by Django 5.2.8 on 2026-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0019_remove_llm_last_ward_lastward'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='last_ward_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
