# Generated by Django 5.2.8 on 2026-02-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0020_llm_last_ward_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llm',
            name='last_ward_is_public',
        ),
        migrations.CreateModel(
            name='UserLastWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('last_ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.lastward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_last_ward',
                'unique_together': {('user', 'last_ward')},
            },
        ),
    ]
