# Generated by Django 5.2.8 on 2026-02-12 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0021_remove_llm_last_ward_is_public_userlastward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ArchivedConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_conversation_id', models.IntegerField(blank=True, null=True, verbose_name='원본 Conversation ID')),
                ('user_text', models.TextField(blank=True, null=True)),
                ('assistant_text', models.TextField(blank=True, null=True)),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='대화 메시지 기록')),
                ('state', models.JSONField(blank=True, default=dict, verbose_name='대화 상태 기록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.llm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보존된 대화 기록',
                'db_table': 'archived_conversation',
                'ordering': ['-archived_at'],
            },
        ),
    ]
