# Generated by Django 5.2.8 on 2026-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_conversation_is_deleted_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='merged_audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/conversation_audio/', verbose_name='병합 오디오'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='merged_audio_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='오디오 제목'),
        ),
    ]
