# Generated by Django 5.2.8 on 2026-02-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0023_add_merged_audio_to_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('conversation', '공유 대화'), ('story', 'AI 스토리'), ('llm', 'AI 캐릭터'), ('snap', '스냅'), ('user', '사용자'), ('comment', '댓글')], max_length=20, verbose_name='콘텐츠 유형')),
                ('content_id', models.CharField(max_length=200, verbose_name='콘텐츠 ID')),
                ('reason', models.CharField(choices=[('spam', '스팸/광고'), ('inappropriate', '부적절한 내용'), ('violence', '폭력적 내용'), ('adult', '성인 콘텐츠'), ('hate', '혐오 발언'), ('other', '기타')], max_length=20, verbose_name='신고 사유')),
                ('description', models.TextField(blank=True, default='', verbose_name='상세 설명')),
                ('status', models.CharField(choices=[('pending', '검토 대기'), ('reviewed', '검토 중'), ('resolved', '처리 완료')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '신고',
                'db_table': 'content_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
