# Generated by Django 5.2.8 on 2026-02-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0024_add_report_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('conversation', '공유 대화'), ('story', 'AI 스토리'), ('llm', 'AI 캐릭터'), ('snap', '스냅'), ('user', '사용자'), ('comment', '댓글'), ('book', '오디오북')], max_length=20, verbose_name='콘텐츠 유형'),
        ),
    ]
