# Generated by Django 5.2.8 on 2026-05-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_content_tts_audio_file'),
        ('character', '0025_alter_report_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='linked_book',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ai_stories',
                to='book.books',
                verbose_name='연결된 웹소설',
                db_constraint=False,
            ),
        ),
    ]
