# Generated by Django 5.2.8 on 2025-11-30 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('audio_files', models.JSONField(default=list)),
                ('total_duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', '업로드 완료'), ('processing', '전처리 중'), ('training', '학습 중'), ('completed', '완료'), ('failed', '실패')], default='uploaded', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('config_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='generated_audio/')),
                ('duration', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compute_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('voice_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice.voiceprofile')),
            ],
        ),
    ]
